version: '3'

services:
  openweather:
    container_name: openweather
    build: .
    volumes:
       - .:/producer
    environment:
      KAFKA_BROKER_URL: localhost:29092
      TOPIC_NAME: "${WEATHER_TOPIC}"
      SLEEP_TIME: ${WEATHER_SLEEP_TIME}

# networks:
#   default:
#     external:
#       name: kafka-network
